<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cart_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cart by id_cart
     */
    function get_cart($id_cart)
    {
        return $this->db->get_where('cart',array('id_cart'=>$id_cart))->row_array();
    }
        
    /*
     * Get all cart
     */
    function get_all_cart()
    {
        $this->db->order_by('id_cart', 'desc');
        return $this->db->get('cart')->result_array();
    }
        
    /*
     * function to add new cart
     */
    function add_cart($params)
    {
        $this->db->insert('cart',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cart
     */
    function update_cart($id_cart,$params)
    {
        $this->db->where('id_cart',$id_cart);
        return $this->db->update('cart',$params);
    }
    
    /*
     * function to delete cart
     */
    function delete_cart($id_cart)
    {
        return $this->db->delete('cart',array('id_cart'=>$id_cart));
    }
}
