<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cart_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cart by id_cart
     */
    function get_cart($id_cart)
    {
        $cart = $this->db->query("
            SELECT
                *

            FROM
                `cart`

            WHERE
                `id_cart` = ?
        ",array($id_cart))->row_array();

        return $cart;
    }
    
    /*
     * Get all cart count
     */
    function get_all_cart_count()
    {
        $cart = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `cart`
        ")->row_array();

        return $cart['count'];
    }
        
    /*
     * Get all cart
     */
    function get_all_cart($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $cart = $this->db->query("
            SELECT
                *

            FROM
                `cart`

            WHERE
                1 = 1

            ORDER BY `id_cart` DESC

            " . $limit_condition . "
        ")->result_array();

        return $cart;
    }
        
    /*
     * function to add new cart
     */
    function add_cart($params)
    {
        $this->db->insert('cart',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cart
     */
    function update_cart($id_cart,$params)
    {
        $this->db->where('id_cart',$id_cart);
        return $this->db->update('cart',$params);
    }
    
    /*
     * function to delete cart
     */
    function delete_cart($id_cart)
    {
        return $this->db->delete('cart',array('id_cart'=>$id_cart));
    }
}
