<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get category by id_cat
     */
    function get_category($id_cat)
    {
        return $this->db->get_where('category',array('id_cat'=>$id_cat))->row_array();
    }
        
    /*
     * Get all category
     */
    function get_all_category()
    {
        $this->db->order_by('id_cat', 'desc');
        return $this->db->get('category')->result_array();
    }
        
    /*
     * function to add new category
     */
    function add_category($params)
    {
        $this->db->insert('category',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update category
     */
    function update_category($id_cat,$params)
    {
        $this->db->where('id_cat',$id_cat);
        return $this->db->update('category',$params);
    }
    
    /*
     * function to delete category
     */
    function delete_category($id_cat)
    {
        return $this->db->delete('category',array('id_cat'=>$id_cat));
    }
}
