<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Feature_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get feature by id_name_har
     */
    function get_feature($id_name_har)
    {
        $feature = $this->db->query("
            SELECT
                *

            FROM
                `feature`

            WHERE
                `id_name_har` = ?
        ",array($id_name_har))->row_array();

        return $feature;
    }
        
    /*
     * Get all feature
     */
    function get_all_feature()
    {
        $feature = $this->db->query("
            SELECT
                *

            FROM
                `feature`

            WHERE
                1 = 1

            ORDER BY `id_name_har` DESC
        ")->result_array();

        return $feature;
    }
        
    /*
     * function to add new feature
     */
    function add_feature($params)
    {
        $this->db->insert('feature',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update feature
     */
    function update_feature($id_name_har,$params)
    {
        $this->db->where('id_name_har',$id_name_har);
        return $this->db->update('feature',$params);
    }
    
    /*
     * function to delete feature
     */
    function delete_feature($id_name_har)
    {
        return $this->db->delete('feature',array('id_name_har'=>$id_name_har));
    }
}
