<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class News_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get news by id_news
     */
    function get_news($id_news)
    {
        $news = $this->db->query("
            SELECT
                *

            FROM
                `news`

            WHERE
                `id_news` = ?
        ",array($id_news))->row_array();

        return $news;
    }
        
    /*
     * Get all news
     */
    function get_all_news()
    {
        $news = $this->db->query("
            SELECT
                *

            FROM
                `news`

            WHERE
                1 = 1

            ORDER BY `id_news` DESC
        ")->result_array();

        return $news;
    }
        
    /*
     * function to add new news
     */
    function add_news($params)
    {
        $this->db->insert('news',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update news
     */
    function update_news($id_news,$params)
    {
        $this->db->where('id_news',$id_news);
        return $this->db->update('news',$params);
    }
    
    /*
     * function to delete news
     */
    function delete_news($id_news)
    {
        return $this->db->delete('news',array('id_news'=>$id_news));
    }
}
