<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class News_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get news by id_news
     */
    function get_news($id_news)
    {
        return $this->db->get_where('news',array('id_news'=>$id_news))->row_array();
    }
        
    /*
     * Get all news
     */
    function get_all_news()
    {
        $this->db->order_by('id_news', 'desc');
        return $this->db->get('news')->result_array();
    }
        
    /*
     * function to add new news
     */
    function add_news($params)
    {
        $this->db->insert('news',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update news
     */
    function update_news($id_news,$params)
    {
        $this->db->where('id_news',$id_news);
        return $this->db->update('news',$params);
    }
    
    /*
     * function to delete news
     */
    function delete_news($id_news)
    {
        return $this->db->delete('news',array('id_news'=>$id_news));
    }
}
