<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Product_cat_link_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get product_cat_link by id_link
     */
    function get_product_cat_link($id_link)
    {
        return $this->db->get_where('product_cat_link',array('id_link'=>$id_link))->row_array();
    }
        
    /*
     * Get all product_cat_link
     */
    function get_all_product_cat_link()
    {
        $this->db->order_by('id_link', 'desc');
        return $this->db->get('product_cat_link')->result_array();
    }
        
    /*
     * function to add new product_cat_link
     */
    function add_product_cat_link($params)
    {
        $this->db->insert('product_cat_link',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update product_cat_link
     */
    function update_product_cat_link($id_link,$params)
    {
        $this->db->where('id_link',$id_link);
        return $this->db->update('product_cat_link',$params);
    }
    
    /*
     * function to delete product_cat_link
     */
    function delete_product_cat_link($id_link)
    {
        return $this->db->delete('product_cat_link',array('id_link'=>$id_link));
    }
}
