<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Product_feature_val_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get product_feature_val by idd
     */
    function get_product_feature_val($idd)
    {
        return $this->db->get_where('product_feature_val',array('idd'=>$idd))->row_array();
    }
        
    /*
     * Get all product_feature_val
     */
    function get_all_product_feature_val()
    {
        $this->db->order_by('idd', 'desc');
        return $this->db->get('product_feature_val')->result_array();
    }
        
    /*
     * function to add new product_feature_val
     */
    function add_product_feature_val($params)
    {
        $this->db->insert('product_feature_val',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update product_feature_val
     */
    function update_product_feature_val($idd,$params)
    {
        $this->db->where('idd',$idd);
        return $this->db->update('product_feature_val',$params);
    }
    
    /*
     * function to delete product_feature_val
     */
    function delete_product_feature_val($idd)
    {
        return $this->db->delete('product_feature_val',array('idd'=>$idd));
    }
}
