<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Product_cat_link_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get product_cat_link by id_link
     */
    function get_product_cat_link($id_link)
    {
        $product_cat_link = $this->db->query("
            SELECT
                *

            FROM
                `product_cat_link`

            WHERE
                `id_link` = ?
        ",array($id_link))->row_array();

        return $product_cat_link;
    }
        
    /*
     * Get all product_cat_link
     */
    function get_all_product_cat_link()
    {
        $product_cat_link = $this->db->query("
            SELECT
                *

            FROM
                `product_cat_link`

            WHERE
                1 = 1

            ORDER BY `id_link` DESC
        ")->result_array();

        return $product_cat_link;
    }
        
    /*
     * function to add new product_cat_link
     */
    function add_product_cat_link($params)
    {
        $this->db->insert('product_cat_link',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update product_cat_link
     */
    function update_product_cat_link($id_link,$params)
    {
        $this->db->where('id_link',$id_link);
        return $this->db->update('product_cat_link',$params);
    }
    
    /*
     * function to delete product_cat_link
     */
    function delete_product_cat_link($id_link)
    {
        return $this->db->delete('product_cat_link',array('id_link'=>$id_link));
    }
}
