<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sub_cat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sub_cat by id_sub
     */
    function get_sub_cat($id_sub)
    {
        return $this->db->get_where('sub_cat',array('id_sub'=>$id_sub))->row_array();
    }
        
    /*
     * Get all sub_cat
     */
    function get_all_sub_cat()
    {
        $this->db->order_by('id_sub', 'desc');
        return $this->db->get('sub_cat')->result_array();
    }
        
    /*
     * function to add new sub_cat
     */
    function add_sub_cat($params)
    {
        $this->db->insert('sub_cat',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sub_cat
     */
    function update_sub_cat($id_sub,$params)
    {
        $this->db->where('id_sub',$id_sub);
        return $this->db->update('sub_cat',$params);
    }
    
    /*
     * function to delete sub_cat
     */
    function delete_sub_cat($id_sub)
    {
        return $this->db->delete('sub_cat',array('id_sub'=>$id_sub));
    }
}
