<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by id_user
     */
    function get_user($id_user)
    {
        $user = $this->db->query("
            SELECT
                *

            FROM
                `users`

            WHERE
                `id_user` = ?
        ",array($id_user))->row_array();

        return $user;
    }
        
    /*
     * Get all users
     */
    function get_all_users()
    {
        $users = $this->db->query("
            SELECT
                *

            FROM
                `users`

            WHERE
                1 = 1

            ORDER BY `id_user` DESC
        ")->result_array();

        return $users;
    }
        
    /*
     * function to add new user
     */
    function add_user($params)
    {
        $this->db->insert('users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user
     */
    function update_user($id_user,$params)
    {
        $this->db->where('id_user',$id_user);
        return $this->db->update('users',$params);
    }
    
    /*
     * function to delete user
     */
    function delete_user($id_user)
    {
        return $this->db->delete('users',array('id_user'=>$id_user));
    }
}
