<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cart extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cart_model');
    } 

    /*
     * Listing of cart
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('cart/index?');
        $config['total_rows'] = $this->Cart_model->get_all_cart_count();
        $this->pagination->initialize($config);

        $data['cart'] = $this->Cart_model->get_all_cart($params);
        
        $data['_view'] = 'cart/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new cart
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_product' => $this->input->post('id_product'),
				'count_product' => $this->input->post('count_product'),
				'price' => $this->input->post('price'),
				'img' => $this->input->post('img'),
				'user' => $this->input->post('user'),
            );
            
            $cart_id = $this->Cart_model->add_cart($params);
            redirect('cart/index');
        }
        else
        {            
            $data['_view'] = 'cart/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a cart
     */
    function edit($id_cart)
    {   
        // check if the cart exists before trying to edit it
        $data['cart'] = $this->Cart_model->get_cart($id_cart);
        
        if(isset($data['cart']['id_cart']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_product' => $this->input->post('id_product'),
					'count_product' => $this->input->post('count_product'),
					'price' => $this->input->post('price'),
					'img' => $this->input->post('img'),
					'user' => $this->input->post('user'),
                );

                $this->Cart_model->update_cart($id_cart,$params);            
                redirect('cart/index');
            }
            else
            {
                $data['_view'] = 'cart/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The cart you are trying to edit does not exist.');
    } 

    /*
     * Deleting cart
     */
    function remove($id_cart)
    {
        $cart = $this->Cart_model->get_cart($id_cart);

        // check if the cart exists before trying to delete it
        if(isset($cart['id_cart']))
        {
            $this->Cart_model->delete_cart($id_cart);
            redirect('cart/index');
        }
        else
            show_error('The cart you are trying to delete does not exist.');
    }
    
}
