<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Category extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Category_model');
    } 

    /*
     * Listing of category
     */
    function index()
    {
        $data['category'] = $this->Category_model->get_all_category();
        
        $data['_view'] = 'category/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new category
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name_cat_ru' => $this->input->post('name_cat_ru'),
				'desc_cat_ru' => $this->input->post('desc_cat_ru'),
				'name_cat_ua' => $this->input->post('name_cat_ua'),
				'desc_cat_ua' => $this->input->post('desc_cat_ua'),
            );
            
            $category_id = $this->Category_model->add_category($params);
            redirect('category/index');
        }
        else
        {            
            $data['_view'] = 'category/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a category
     */
    function edit($id_cat)
    {   
        // check if the category exists before trying to edit it
        $data['category'] = $this->Category_model->get_category($id_cat);
        
        if(isset($data['category']['id_cat']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name_cat_ru' => $this->input->post('name_cat_ru'),
					'desc_cat_ru' => $this->input->post('desc_cat_ru'),
					'name_cat_ua' => $this->input->post('name_cat_ua'),
					'desc_cat_ua' => $this->input->post('desc_cat_ua'),
                );

                $this->Category_model->update_category($id_cat,$params);            
                redirect('category/index');
            }
            else
            {
                $data['_view'] = 'category/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The category you are trying to edit does not exist.');
    } 

    /*
     * Deleting category
     */
    function remove($id_cat)
    {
        $category = $this->Category_model->get_category($id_cat);

        // check if the category exists before trying to delete it
        if(isset($category['id_cat']))
        {
            $this->Category_model->delete_category($id_cat);
            redirect('category/index');
        }
        else
            show_error('The category you are trying to delete does not exist.');
    }
    
}
