<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Feature extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Feature_model');
    } 

    /*
     * Listing of feature
     */
    function index()
    {
        $data['feature'] = $this->Feature_model->get_all_feature();
        
        $data['_view'] = 'feature/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new feature
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name_har_ua' => $this->input->post('name_har_ua'),
				'name_har_ru' => $this->input->post('name_har_ru'),
            );
            
            $feature_id = $this->Feature_model->add_feature($params);
            redirect('feature/index');
        }
        else
        {            
            $data['_view'] = 'feature/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a feature
     */
    function edit($id_name_har)
    {   
        // check if the feature exists before trying to edit it
        $data['feature'] = $this->Feature_model->get_feature($id_name_har);
        
        if(isset($data['feature']['id_name_har']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name_har_ua' => $this->input->post('name_har_ua'),
					'name_har_ru' => $this->input->post('name_har_ru'),
                );

                $this->Feature_model->update_feature($id_name_har,$params);            
                redirect('feature/index');
            }
            else
            {
                $data['_view'] = 'feature/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The feature you are trying to edit does not exist.');
    } 

    /*
     * Deleting feature
     */
    function remove($id_name_har)
    {
        $feature = $this->Feature_model->get_feature($id_name_har);

        // check if the feature exists before trying to delete it
        if(isset($feature['id_name_har']))
        {
            $this->Feature_model->delete_feature($id_name_har);
            redirect('feature/index');
        }
        else
            show_error('The feature you are trying to delete does not exist.');
    }
    
}
