<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class News extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('News_model');
    } 

    /*
     * Listing of news
     */
    function index()
    {
        $data['news'] = $this->News_model->get_all_news();
        
        $data['_view'] = 'news/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new news
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'keywords_news_ua' => $this->input->post('keywords_news_ua'),
				'keywords_news_ru' => $this->input->post('keywords_news_ru'),
				'description_news_ua' => $this->input->post('description_news_ua'),
				'description_news_ru' => $this->input->post('description_news_ru'),
				'title_news_ua' => $this->input->post('title_news_ua'),
				'title_news_ru' => $this->input->post('title_news_ru'),
				'img_news' => $this->input->post('img_news'),
				'text_news_ua' => $this->input->post('text_news_ua'),
				'text_news_ru' => $this->input->post('text_news_ru'),
            );
            
            $news_id = $this->News_model->add_news($params);
            redirect('news/index');
        }
        else
        {            
            $data['_view'] = 'news/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a news
     */
    function edit($id_news)
    {   
        // check if the news exists before trying to edit it
        $data['news'] = $this->News_model->get_news($id_news);
        
        if(isset($data['news']['id_news']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'keywords_news_ua' => $this->input->post('keywords_news_ua'),
					'keywords_news_ru' => $this->input->post('keywords_news_ru'),
					'description_news_ua' => $this->input->post('description_news_ua'),
					'description_news_ru' => $this->input->post('description_news_ru'),
					'title_news_ua' => $this->input->post('title_news_ua'),
					'title_news_ru' => $this->input->post('title_news_ru'),
					'img_news' => $this->input->post('img_news'),
					'text_news_ua' => $this->input->post('text_news_ua'),
					'text_news_ru' => $this->input->post('text_news_ru'),
                );

                $this->News_model->update_news($id_news,$params);            
                redirect('news/index');
            }
            else
            {
                $data['_view'] = 'news/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The news you are trying to edit does not exist.');
    } 

    /*
     * Deleting news
     */
    function remove($id_news)
    {
        $news = $this->News_model->get_news($id_news);

        // check if the news exists before trying to delete it
        if(isset($news['id_news']))
        {
            $this->News_model->delete_news($id_news);
            redirect('news/index');
        }
        else
            show_error('The news you are trying to delete does not exist.');
    }
    
}
