<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Product_cat_link extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Product_cat_link_model');
    } 

    /*
     * Listing of product_cat_link
     */
    function index()
    {
        $data['product_cat_link'] = $this->Product_cat_link_model->get_all_product_cat_link();
        
        $data['_view'] = 'product_cat_link/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new product_cat_link
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_prod' => $this->input->post('id_prod'),
				'id_cat' => $this->input->post('id_cat'),
				'id_sub_cat' => $this->input->post('id_sub_cat'),
				'id_sub_sub_cat' => $this->input->post('id_sub_sub_cat'),
            );
            
            $product_cat_link_id = $this->Product_cat_link_model->add_product_cat_link($params);
            redirect('product_cat_link/index');
        }
        else
        {            
            $data['_view'] = 'product_cat_link/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a product_cat_link
     */
    function edit($id_link)
    {   
        // check if the product_cat_link exists before trying to edit it
        $data['product_cat_link'] = $this->Product_cat_link_model->get_product_cat_link($id_link);
        
        if(isset($data['product_cat_link']['id_link']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_prod' => $this->input->post('id_prod'),
					'id_cat' => $this->input->post('id_cat'),
					'id_sub_cat' => $this->input->post('id_sub_cat'),
					'id_sub_sub_cat' => $this->input->post('id_sub_sub_cat'),
                );

                $this->Product_cat_link_model->update_product_cat_link($id_link,$params);            
                redirect('product_cat_link/index');
            }
            else
            {
                $data['_view'] = 'product_cat_link/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The product_cat_link you are trying to edit does not exist.');
    } 

    /*
     * Deleting product_cat_link
     */
    function remove($id_link)
    {
        $product_cat_link = $this->Product_cat_link_model->get_product_cat_link($id_link);

        // check if the product_cat_link exists before trying to delete it
        if(isset($product_cat_link['id_link']))
        {
            $this->Product_cat_link_model->delete_product_cat_link($id_link);
            redirect('product_cat_link/index');
        }
        else
            show_error('The product_cat_link you are trying to delete does not exist.');
    }
    
}
