<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Product_img extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Product_img_model');
    } 

    /*
     * Listing of product_img
     */
    function index()
    {
        $data['product_img'] = $this->Product_img_model->get_all_product_img();
        
        $data['_view'] = 'product_img/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new product_img
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'prod_id' => $this->input->post('prod_id'),
				'img' => $this->input->post('img'),
            );
            
            $product_img_id = $this->Product_img_model->add_product_img($params);
            redirect('product_img/index');
        }
        else
        {            
            $data['_view'] = 'product_img/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a product_img
     */
    function edit($img_id)
    {   
        // check if the product_img exists before trying to edit it
        $data['product_img'] = $this->Product_img_model->get_product_img($img_id);
        
        if(isset($data['product_img']['img_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'prod_id' => $this->input->post('prod_id'),
					'img' => $this->input->post('img'),
                );

                $this->Product_img_model->update_product_img($img_id,$params);            
                redirect('product_img/index');
            }
            else
            {
                $data['_view'] = 'product_img/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The product_img you are trying to edit does not exist.');
    } 

    /*
     * Deleting product_img
     */
    function remove($img_id)
    {
        $product_img = $this->Product_img_model->get_product_img($img_id);

        // check if the product_img exists before trying to delete it
        if(isset($product_img['img_id']))
        {
            $this->Product_img_model->delete_product_img($img_id);
            redirect('product_img/index');
        }
        else
            show_error('The product_img you are trying to delete does not exist.');
    }
    
}
