<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Product_feature_val extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Product_feature_val_model');
    } 

    /*
     * Listing of product_feature_val
     */
    function index()
    {
        $data['product_feature_val'] = $this->Product_feature_val_model->get_all_product_feature_val();
        
        $data['_view'] = 'product_feature_val/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new product_feature_val
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_product' => $this->input->post('id_product'),
				'id_feature' => $this->input->post('id_feature'),
            );
            
            $product_feature_val_id = $this->Product_feature_val_model->add_product_feature_val($params);
            redirect('product_feature_val/index');
        }
        else
        {            
            $data['_view'] = 'product_feature_val/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a product_feature_val
     */
    function edit($idd)
    {   
        // check if the product_feature_val exists before trying to edit it
        $data['product_feature_val'] = $this->Product_feature_val_model->get_product_feature_val($idd);
        
        if(isset($data['product_feature_val']['idd']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_product' => $this->input->post('id_product'),
					'id_feature' => $this->input->post('id_feature'),
                );

                $this->Product_feature_val_model->update_product_feature_val($idd,$params);            
                redirect('product_feature_val/index');
            }
            else
            {
                $data['_view'] = 'product_feature_val/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The product_feature_val you are trying to edit does not exist.');
    } 

    /*
     * Deleting product_feature_val
     */
    function remove($idd)
    {
        $product_feature_val = $this->Product_feature_val_model->get_product_feature_val($idd);

        // check if the product_feature_val exists before trying to delete it
        if(isset($product_feature_val['idd']))
        {
            $this->Product_feature_val_model->delete_product_feature_val($idd);
            redirect('product_feature_val/index');
        }
        else
            show_error('The product_feature_val you are trying to delete does not exist.');
    }
    
}
