<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sub_cat extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sub_cat_model');
    } 

    /*
     * Listing of sub_cat
     */
    function index()
    {
        $data['sub_cat'] = $this->Sub_cat_model->get_all_sub_cat();
        
        $data['_view'] = 'sub_cat/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new sub_cat
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_cat' => $this->input->post('id_cat'),
				'sub_name_ua' => $this->input->post('sub_name_ua'),
				'sub_name_ru' => $this->input->post('sub_name_ru'),
				'sub_key_ua' => $this->input->post('sub_key_ua'),
				'sub_key_ru' => $this->input->post('sub_key_ru'),
				'sub_desc_ua' => $this->input->post('sub_desc_ua'),
				'sub_desc_ru' => $this->input->post('sub_desc_ru'),
            );
            
            $sub_cat_id = $this->Sub_cat_model->add_sub_cat($params);
            redirect('sub_cat/index');
        }
        else
        {            
            $data['_view'] = 'sub_cat/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a sub_cat
     */
    function edit($id_sub)
    {   
        // check if the sub_cat exists before trying to edit it
        $data['sub_cat'] = $this->Sub_cat_model->get_sub_cat($id_sub);
        
        if(isset($data['sub_cat']['id_sub']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_cat' => $this->input->post('id_cat'),
					'sub_name_ua' => $this->input->post('sub_name_ua'),
					'sub_name_ru' => $this->input->post('sub_name_ru'),
					'sub_key_ua' => $this->input->post('sub_key_ua'),
					'sub_key_ru' => $this->input->post('sub_key_ru'),
					'sub_desc_ua' => $this->input->post('sub_desc_ua'),
					'sub_desc_ru' => $this->input->post('sub_desc_ru'),
                );

                $this->Sub_cat_model->update_sub_cat($id_sub,$params);            
                redirect('sub_cat/index');
            }
            else
            {
                $data['_view'] = 'sub_cat/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The sub_cat you are trying to edit does not exist.');
    } 

    /*
     * Deleting sub_cat
     */
    function remove($id_sub)
    {
        $sub_cat = $this->Sub_cat_model->get_sub_cat($id_sub);

        // check if the sub_cat exists before trying to delete it
        if(isset($sub_cat['id_sub']))
        {
            $this->Sub_cat_model->delete_sub_cat($id_sub);
            redirect('sub_cat/index');
        }
        else
            show_error('The sub_cat you are trying to delete does not exist.');
    }
    
}
