<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Feature_val extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Feature_val_model');
    } 

    /*
     * Listing of feature_val
     */
    function index()
    {
        $data['feature_val'] = $this->Feature_val_model->get_all_feature_val();
        
        $data['_view'] = 'feature_val/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new feature_val
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id' => $this->input->post('id'),
				'id_feature' => $this->input->post('id_feature'),
				'val_feature_ua' => $this->input->post('val_feature_ua'),
				'val_feature_ru' => $this->input->post('val_feature_ru'),
            );
            
            $feature_val_id = $this->Feature_val_model->add_feature_val($params);
            redirect('feature_val/index');
        }
        else
        {            
            $data['_view'] = 'feature_val/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a feature_val
     */
    function edit($)
    {   
        // check if the feature_val exists before trying to edit it
        $data['feature_val'] = $this->Feature_val_model->get_feature_val($);
        
        if(isset($data['feature_val']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id' => $this->input->post('id'),
					'id_feature' => $this->input->post('id_feature'),
					'val_feature_ua' => $this->input->post('val_feature_ua'),
					'val_feature_ru' => $this->input->post('val_feature_ru'),
                );

                $this->Feature_val_model->update_feature_val($,$params);            
                redirect('feature_val/index');
            }
            else
            {
                $data['_view'] = 'feature_val/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The feature_val you are trying to edit does not exist.');
    } 

    /*
     * Deleting feature_val
     */
    function remove($)
    {
        $feature_val = $this->Feature_val_model->get_feature_val($);

        // check if the feature_val exists before trying to delete it
        if(isset($feature_val['']))
        {
            $this->Feature_val_model->delete_feature_val($);
            redirect('feature_val/index');
        }
        else
            show_error('The feature_val you are trying to delete does not exist.');
    }
    
}
