<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sub_sub_cat extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sub_sub_cat_model');
    } 

    /*
     * Listing of sub_sub_cat
     */
    function index()
    {
        $data['sub_sub_cat'] = $this->Sub_sub_cat_model->get_all_sub_sub_cat();
        
        $data['_view'] = 'sub_sub_cat/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new sub_sub_cat
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_sub' => $this->input->post('id_sub'),
				'name_sub_sub_ua' => $this->input->post('name_sub_sub_ua'),
				'name_sub_sub_ru' => $this->input->post('name_sub_sub_ru'),
				'key_sub_sub_ua' => $this->input->post('key_sub_sub_ua'),
				'key_sub_sub_ru' => $this->input->post('key_sub_sub_ru'),
				'desc_sub_sub_ua' => $this->input->post('desc_sub_sub_ua'),
				'desc_sub_sub_ru' => $this->input->post('desc_sub_sub_ru'),
            );
            
            $sub_sub_cat_id = $this->Sub_sub_cat_model->add_sub_sub_cat($params);
            redirect('sub_sub_cat/index');
        }
        else
        {            
            $data['_view'] = 'sub_sub_cat/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a sub_sub_cat
     */
    function edit($id_sub_sub)
    {   
        // check if the sub_sub_cat exists before trying to edit it
        $data['sub_sub_cat'] = $this->Sub_sub_cat_model->get_sub_sub_cat($id_sub_sub);
        
        if(isset($data['sub_sub_cat']['id_sub_sub']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_sub' => $this->input->post('id_sub'),
					'name_sub_sub_ua' => $this->input->post('name_sub_sub_ua'),
					'name_sub_sub_ru' => $this->input->post('name_sub_sub_ru'),
					'key_sub_sub_ua' => $this->input->post('key_sub_sub_ua'),
					'key_sub_sub_ru' => $this->input->post('key_sub_sub_ru'),
					'desc_sub_sub_ua' => $this->input->post('desc_sub_sub_ua'),
					'desc_sub_sub_ru' => $this->input->post('desc_sub_sub_ru'),
                );

                $this->Sub_sub_cat_model->update_sub_sub_cat($id_sub_sub,$params);            
                redirect('sub_sub_cat/index');
            }
            else
            {
                $data['_view'] = 'sub_sub_cat/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The sub_sub_cat you are trying to edit does not exist.');
    } 

    /*
     * Deleting sub_sub_cat
     */
    function remove($id_sub_sub)
    {
        $sub_sub_cat = $this->Sub_sub_cat_model->get_sub_sub_cat($id_sub_sub);

        // check if the sub_sub_cat exists before trying to delete it
        if(isset($sub_sub_cat['id_sub_sub']))
        {
            $this->Sub_sub_cat_model->delete_sub_sub_cat($id_sub_sub);
            redirect('sub_sub_cat/index');
        }
        else
            show_error('The sub_sub_cat you are trying to delete does not exist.');
    }
    
}
