<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sub_sub_cat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sub_sub_cat by id_sub_sub
     */
    function get_sub_sub_cat($id_sub_sub)
    {
        $sub_sub_cat = $this->db->query("
            SELECT
                *

            FROM
                `sub_sub_cat`

            WHERE
                `id_sub_sub` = ?
        ",array($id_sub_sub))->row_array();

        return $sub_sub_cat;
    }
        
    /*
     * Get all sub_sub_cat
     */
    function get_all_sub_sub_cat()
    {
        $sub_sub_cat = $this->db->query("
            SELECT
                *

            FROM
                `sub_sub_cat`

            WHERE
                1 = 1

            ORDER BY `id_sub_sub` DESC
        ")->result_array();

        return $sub_sub_cat;
    }
        
    /*
     * function to add new sub_sub_cat
     */
    function add_sub_sub_cat($params)
    {
        $this->db->insert('sub_sub_cat',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sub_sub_cat
     */
    function update_sub_sub_cat($id_sub_sub,$params)
    {
        $this->db->where('id_sub_sub',$id_sub_sub);
        return $this->db->update('sub_sub_cat',$params);
    }
    
    /*
     * function to delete sub_sub_cat
     */
    function delete_sub_sub_cat($id_sub_sub)
    {
        return $this->db->delete('sub_sub_cat',array('id_sub_sub'=>$id_sub_sub));
    }
}
